### ISSUE TITLE
Copy Edit Readme

### ISSUE THREAD

**Issue by acrosman** [acrosman/sc_salary_data#1]
The readme file could use to have a good copy edit done.

**Comment by JayStag** [comment]
@acrosman I can help you with this.

**Comment by acrosman** [comment]
@JayStag I'm always happy to have more edits to any of my docs. If you're still interested in provided a PR on this please feel free.

**Comment by JayStag** [comment]
@acrosman Thank you. I will take a look and help where I can. 👍
