### ISSUE TITLE
Fix Code Standard

### ISSUE THREAD

**Issue by acrosman** [acrosman/sc_salary_data#2]
This project should conform to Flake8 but doesn't in some places.

**Comment by SanchitJain123** [comment]
Hey @acrosman, can I work on this

**Comment by acrosman** [comment]
Thanks, that's great. This is intended to be part of [Hacktoberfest](https://hacktoberfest.digitalocean.com/), so you are participating you might wait until it starts to open a PR.

**Comment by SanchitJain123** [comment]
@acrosman, please assign me to this. Sure, I'll open PR during Hacktoberfest :)
