### ISSUE TITLE
Clean up file names

### ISSUE THREAD

**Issue by acrosman** [acrosman/sc_salary_data#8]
The `raw_data` directory has gotten to the point that the file names are inconsistent.  They should be updated to remove `%20` and replace with a ` ` [space].

**Comment by andrefpoliveira** [comment]
Hey! Can I work on this together with #9 as part of my journey through Hacktoberfest 2022?

**Comment by andrefpoliveira** [comment]
While taking a look at the files, I noticed that you have 2 files that will cause a conflict: `Transparency Salary Data 10.7.2020.csv` and `Transparency%20Salary%20Data%2010.7.2020.csv`. Both of these files will have the same name after the clean-up. Do you have any preference on the file you want to keep? The only difference between them is a few characters in the beginning of the file.

**Comment by acrosman** [comment]
Closed by #11
