### ISSUE TITLE
Fix file naming on extraction

### ISSUE THREAD

**Issue by acrosman** [acrosman/sc_salary_data#9]
The process in `get_salary_data.py` is doing a nice job of pulling data from the state's servers on a regular basis. But #8 is caused by the fact that it's not handling file names well.  File names should be consistent when saved to disk.  Please update the process to make sure the files are consistently named, and artifacts like `%20` from the URL are properly decoded.

**Comment by andrefpoliveira** [comment]
Hey! Could I work on this as part of my journey through Hacktoberfest 2022?

**Comment by acrosman** [comment]
Closed by #10
